version: '3.1'

services:
  mysql-db:
    image: mysql
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: migration_data
  cassandra-db:
    image: cassandra
    ports:
      - 39042:9042
